// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhycdecaclsriddmgroc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeWNkZWNhY2xzcmlkZG1ncm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTUyOTIsImV4cCI6MjA2NDQ3MTI5Mn0.EPk-lKBFen0cN4wgeQfOCwsOdHfZJB7v1be3UyU99bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);